version: '3'
services:
    db:
      image: postgres:18.1
      container_name: lil-postgres
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=ROOT
        - POSTGRES_DB=lil
      ports:
        - 127.0.0.1:65432:5432
